version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: amongus-db
    environment:
      POSTGRES_DB: amongus
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
